# Generated by Django 4.0.4 on 2022-09-09 04:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='age',
            field=models.CharField(default=datetime.datetime(2022, 9, 9, 4, 15, 29, 909750, tzinfo=utc), max_length=3),
            preserve_default=False,
        ),
    ]
