# Generated by Django 4.0.4 on 2022-09-09 19:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_candidate_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='phone',
            field=models.CharField(default=datetime.datetime(2022, 9, 9, 19, 24, 5, 440057, tzinfo=utc), max_length=25),
            preserve_default=False,
        ),
    ]
