# Generated by Django 4.0.4 on 2022-09-09 23:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_candidate_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='job',
            field=models.CharField(default=datetime.datetime(2022, 9, 9, 23, 32, 9, 669500, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
    ]
