# Generated by Django 4.0.4 on 2022-09-13 19:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_candidate_experience_candidate_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='file',
            field=models.FileField(default=datetime.datetime(2022, 9, 13, 19, 56, 32, 591750, tzinfo=utc), upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='Situation',
            field=models.CharField(choices=[('Disapproved', 'Disapproved'), ('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='personality',
            field=models.CharField(choices=[('', 'Select a personality'), ('I am serious', 'I am serious'), ('I am discreet', 'I am discreet'), ('I am antisocial', 'I am antisocial'), ('I am outgoing', 'I am outgoing'), ('I am sociable', 'I am sociable')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='smoker',
            field=models.CharField(choices=[('2', 'No'), ('1', 'Yes')], default='', max_length=10),
        ),
    ]
