# Generated by Django 4.0.4 on 2022-09-16 19:07

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_candidate_file_alter_candidate_situation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='databases',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Oracle', 'Oracle'), ('MongoDB', 'MongoDB'), ('Others', 'Others'), ('SqlLite3', 'SqlLite3'), ('PostGree', 'PostGree'), ('MySql', 'MySql')], default='', max_length=45),
        ),
        migrations.AddField(
            model_name='candidate',
            name='frameworks',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Laravel', 'Laravel'), ('Django', 'Django'), ('Others', 'Others'), ('FastAPI', 'FastAPI'), ('Vue', 'Vue'), ('Angular', 'Angular')], default='', max_length=41),
        ),
        migrations.AddField(
            model_name='candidate',
            name='languages',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Ruby', 'Ruby'), ('C++', 'C++'), ('Others', 'Others'), ('Python', 'Python'), ('Javascript', 'Javascript'), ('Java', 'Java')], default='', max_length=38),
        ),
        migrations.AddField(
            model_name='candidate',
            name='libraries',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Jquery', 'Jquery'), ('Ajax', 'Ajax'), ('Others', 'Others'), ('Gsap', 'Gsap'), ('Chart.js', 'Chart.js'), ('React.js', 'React.js')], default='', max_length=41),
        ),
        migrations.AddField(
            model_name='candidate',
            name='mobile',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('React Native', 'React Native'), ('Xamarin', 'Xamarin'), ('Flutter', 'Flutter'), ('Others', 'Others'), ('Kivy', 'Kivy'), ('Ionic', 'Ionic')], default='', max_length=46),
        ),
        migrations.AddField(
            model_name='candidate',
            name='others',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('UML', 'UML'), ('GraphSQL', 'GraphSQL'), ('Others', 'Others'), ('DOCKER', 'DOCKER'), ('GIT', 'GIT'), ('SQL', 'SQL')], default='', max_length=34),
        ),
    ]
