# Generated by Django 4.0.4 on 2022-09-21 19:12

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_candidate_databases_candidate_frameworks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='company_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='Situation',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Disapproved', 'Disapproved')], default='Pending', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='databases',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('PostGree', 'PostGree'), ('Others', 'Others'), ('MySql', 'MySql'), ('MongoDB', 'MongoDB'), ('SqlLite3', 'SqlLite3'), ('Oracle', 'Oracle')], default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='frameworks',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Angular', 'Angular'), ('FastAPI', 'FastAPI'), ('Django', 'Django'), ('Vue', 'Vue'), ('Others', 'Others'), ('Laravel', 'Laravel')], default='', max_length=41),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='languages',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Java', 'Java'), ('C++', 'C++'), ('Python', 'Python'), ('Others', 'Others'), ('Ruby', 'Ruby'), ('Javascript', 'Javascript')], default='', max_length=38),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='libraries',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Gsap', 'Gsap'), ('Others', 'Others'), ('Chart.js', 'Chart.js'), ('Ajax', 'Ajax'), ('Jquery', 'Jquery'), ('React.js', 'React.js')], default='', max_length=41),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='mobile',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('React Native', 'React Native'), ('Kivy', 'Kivy'), ('Others', 'Others'), ('Xamarin', 'Xamarin'), ('Ionic', 'Ionic'), ('Flutter', 'Flutter')], default='', max_length=46),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='others',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('DOCKER', 'DOCKER'), ('GIT', 'GIT'), ('Others', 'Others'), ('UML', 'UML'), ('SQL', 'SQL'), ('GraphSQL', 'GraphSQL')], default='', max_length=34),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='personality',
            field=models.CharField(choices=[('', 'Select a personality'), ('I am discreet', 'I am discreet'), ('I am serious', 'I am serious'), ('I am antisocial', 'I am antisocial'), ('I am outgoing', 'I am outgoing'), ('I am sociable', 'I am sociable')], max_length=50, null=True),
        ),
    ]
