# Generated by Django 4.0.4 on 2022-09-25 06:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_remove_candidate_age_candidate_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='about_course',
            field=models.CharField(default=datetime.datetime(2022, 9, 25, 6, 12, 2, 3000, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='company',
            field=models.CharField(default=datetime.datetime(2022, 9, 25, 6, 12, 15, 302000, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='course',
            field=models.CharField(default=datetime.datetime(2022, 9, 25, 6, 12, 22, 738000, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='employed',
            field=models.BooleanField(null=True, verbose_name='I am employed'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='finished_course',
            field=models.DateField(default=datetime.datetime(2022, 9, 25, 6, 12, 27, 931000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='finished_job',
            field=models.DateField(default=datetime.datetime(2022, 9, 25, 6, 12, 38, 508000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='institution',
            field=models.CharField(default=datetime.datetime(2022, 9, 25, 6, 12, 44, 90000, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='position',
            field=models.CharField(default=datetime.datetime(2022, 9, 25, 6, 12, 48, 347000, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='remote',
            field=models.BooleanField(null=True, verbose_name='I agree remote to work remotely'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='started_course',
            field=models.DateField(default=datetime.datetime(2022, 9, 25, 6, 12, 52, 828000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='started_job',
            field=models.DateField(default=datetime.datetime(2022, 9, 25, 6, 12, 56, 469000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='status_course',
            field=models.CharField(choices=[('I am broke', 'I am broke'), ('I am complete', 'I am complete'), ('I am student', 'I am student'), ('', 'Select your status')], default=datetime.datetime(2022, 9, 25, 6, 12, 59, 498000, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='travel',
            field=models.BooleanField(null=True, verbose_name="I' m avaible for travel"),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='Situation',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Disapproved', 'Disapproved')], default='Pending', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='databases',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('PostGree', 'PostGree'), ('MySql', 'MySql'), ('MongoDB', 'MongoDB'), ('SqlLite3', 'SqlLite3'), ('Others', 'Others'), ('Oracle', 'Oracle')], default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='frameworks',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Django', 'Django'), ('Laravel', 'Laravel'), ('Vue', 'Vue'), ('Angular', 'Angular'), ('Others', 'Others'), ('FastAPI', 'FastAPI')], default='', max_length=41),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='languages',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Javascript', 'Javascript'), ('Python', 'Python'), ('Java', 'Java'), ('Others', 'Others'), ('Ruby', 'Ruby'), ('C++', 'C++')], default='', max_length=38),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='libraries',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Gsap', 'Gsap'), ('Ajax', 'Ajax'), ('Chart.js', 'Chart.js'), ('Others', 'Others'), ('React.js', 'React.js'), ('Jquery', 'Jquery')], default='', max_length=41),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='mobile',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('React Native', 'React Native'), ('Ionic', 'Ionic'), ('Kivy', 'Kivy'), ('Flutter', 'Flutter'), ('Others', 'Others'), ('Xamarin', 'Xamarin')], default='', max_length=46),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='others',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('SQL', 'SQL'), ('GraphSQL', 'GraphSQL'), ('Others', 'Others'), ('DOCKER', 'DOCKER'), ('GIT', 'GIT'), ('UML', 'UML')], default='', max_length=34),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='personality',
            field=models.CharField(choices=[('I am discreet', 'I am discreet'), ('I am outgoing', 'I am outgoing'), ('I am antisocial', 'I am antisocial'), ('', 'Select a personality'), ('I am serious', 'I am serious'), ('I am sociable', 'I am sociable')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='smoker',
            field=models.CharField(choices=[('1', 'Yes'), ('2', 'No')], default='', max_length=10),
        ),
    ]
