# Generated by Django 4.0.4 on 2022-09-25 06:28

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_candidate_about_course_candidate_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='image',
            field=models.ImageField(blank=True, upload_to='photo', verbose_name='Potho'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='Situation',
            field=models.CharField(choices=[('Disapproved', 'Disapproved'), ('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='databases',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Others', 'Others'), ('MongoDB', 'MongoDB'), ('SqlLite3', 'SqlLite3'), ('MySql', 'MySql'), ('PostGree', 'PostGree'), ('Oracle', 'Oracle')], default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='file',
            field=models.FileField(blank=True, upload_to='resume', verbose_name='Resume'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='frameworks',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Others', 'Others'), ('Vue', 'Vue'), ('Django', 'Django'), ('Laravel', 'Laravel'), ('FastAPI', 'FastAPI'), ('Angular', 'Angular')], default='', max_length=41),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='languages',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Others', 'Others'), ('Java', 'Java'), ('Python', 'Python'), ('Javascript', 'Javascript'), ('C++', 'C++'), ('Ruby', 'Ruby')], default='', max_length=38),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='libraries',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Others', 'Others'), ('Jquery', 'Jquery'), ('Gsap', 'Gsap'), ('React.js', 'React.js'), ('Chart.js', 'Chart.js'), ('Ajax', 'Ajax')], default='', max_length=41),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='mobile',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Others', 'Others'), ('React Native', 'React Native'), ('Flutter', 'Flutter'), ('Kivy', 'Kivy'), ('Ionic', 'Ionic'), ('Xamarin', 'Xamarin')], default='', max_length=46),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='others',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('GIT', 'GIT'), ('Others', 'Others'), ('SQL', 'SQL'), ('GraphSQL', 'GraphSQL'), ('DOCKER', 'DOCKER'), ('UML', 'UML')], default='', max_length=34),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='personality',
            field=models.CharField(choices=[('I am discreet', 'I am discreet'), ('I am serious', 'I am serious'), ('I am antisocial', 'I am antisocial'), ('I am sociable', 'I am sociable'), ('I am outgoing', 'I am outgoing'), ('', 'Select a personality')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status_course',
            field=models.CharField(choices=[('I am student', 'I am student'), ('I am broke', 'I am broke'), ('I am complete', 'I am complete'), ('', 'Select your status')], max_length=50),
        ),
    ]
